export function getImageSource(imgsource: string){
    switch (imgsource) { 
        case 'pc-breeze-api-w-next.png':
            return require('@/assets/images/projects/pc-breeze-api-w-next.png');
        case 'pc-chirper-api-w-next.png':
            return require('@/assets/images/projects/pc-chirper-api-w-next.png');
        case 'pc-chirper-laravel-jwt.png':
            return require('@/assets/images/projects/pc-chirper-laravel-jwt.png');
        case 'pc-chirper-laravel-next.png':
            return require('@/assets/images/projects/pc-chirper-laravel-next.png');
        case 'pc-chirper-next-fullstack.png':
            return require('@/assets/images/projects/pc-chirper-next-fullstack.png');
        case 'pc-firebase-auth-email.png':
            return require('@/assets/images/projects/pc-firebase-auth-email.png');
        case 'm-firebase-auth-email.png':
            return require('@/assets/images/projects/m-firebase-auth-email.png');
        case 'pc-firebase-auth.png':
            return require('@/assets/images/projects/pc-firebase-auth.png');
        case 'm-firebase-auth.png':
            return require('@/assets/images/projects/m-firebase-auth.png');
        case 'pc-firebase-realtime-chat.png':
            return require('@/assets/images/projects/pc-firebase-realtime-chat.png');
        case 'pc-firestore-realtime-chat.png':
            return require('@/assets/images/projects/pc-firestore-realtime-chat.png');
        case 'm-firestore-realtime-chat.png':
            return require('@/assets/images/projects/m-firestore-realtime-chat.png');
        case 'pc-hackernews-nextjs-apollo.png':
            return require('@/assets/images/projects/pc-hackernews-nextjs-apollo.png');
        case 'm-hackernews-apollo.png':
            return require('@/assets/images/projects/m-hackernews-apollo.png');
        case 'pc-meal-delivery.png':
            return require('@/assets/images/projects/pc-meal-delivery.png');
        case 'm-meal-delivery.png':
            return require('@/assets/images/projects/m-meal-delivery.png');
        case 'pc-nextjs-projects.png':
            return require('@/assets/images/projects/pc-nextjs-projects.png');
        case 'm-nextjs-projects.png':
            return require('@/assets/images/projects/m-nextjs-projects.png');
        case 'pc-nextjs-socket-chat.png':
            return require('@/assets/images/projects/pc-nextjs-socket-chat.png');
        case 'pc-projects-jglchen.png':
            return require('@/assets/images/projects/pc-projects-jglchen.png');
        case 'pc-react-app-demo.png':
            return require('@/assets/images/projects/pc-react-app-demo.png');
        case 'm-react-app-demo.png':
            return require('@/assets/images/projects/m-react-app-demo.png');
        case 'pc-react-md-editor.png':
            return require('@/assets/images/projects/pc-react-md-editor.png');
        case 'm-react-md-editor.png':
            return require('@/assets/images/projects/m-react-md-editor.png');
        case 'pc-realtime-stock-next.png':
            return require('@/assets/images/projects/pc-realtime-stock-next.png');
        case 'pc-scheduler-app.png':
            return require('@/assets/images/projects/pc-scheduler-app.png');
        case 'm-scheduler-app.png':
            return require('@/assets/images/projects/m-scheduler-app.png');
        case 'pc-user-laravel-jwt.png':
            return require('@/assets/images/projects/pc-user-laravel-jwt.png');
        case 'pc-user-laravel-next.png':
            return require('@/assets/images/projects/pc-user-laravel-next.png');
        case 'pc-user-next-fullstack.png':
            return require('@/assets/images/projects/pc-user-next-fullstack.png');
        case 'pc-web-scrape.png':
            return require('@/assets/images/projects/pc-web-scrape.png');
        case 'm-web-scrape.png':
            return require('@/assets/images/projects/m-web-scrape.png');
 
        case 'css3.png':
            return require('@/assets/images/skills/css3.png');
        case 'tailwindcss.png':
            return require('@/assets/images/skills/tailwindcss.png');
        case 'html5.png':
            return require('@/assets/images/skills/html5.png');
        case 'javascript.webp':
            return require('@/assets/images/skills/javascript.webp');
        case 'typescript.png':
            return require('@/assets/images/skills/typescript.png');
        case 'node-hexagon.png':
            return require('@/assets/images/skills/node-hexagon.png');
        case 'react-js.png':
            return require('@/assets/images/skills/react-js.png');
        case 'nextjs-icon.png':
            return require('@/assets/images/skills/nextjs-icon.png');
        case 'express-js.png':
            return require('@/assets/images/skills/express-js.png');
        case 'react-native.png':
            return require('@/assets/images/skills/react-native.png');
        case 'sql.webp':
            return require('@/assets/images/skills/sql.webp');
        case 'mysql-round.png':
            return require('@/assets/images/skills/mysql-round.png');
        case 'firebase.webp':
            return require('@/assets/images/skills/firebase.webp');
        case 'docker.png':
            return require('@/assets/images/skills/docker.png');
        case 'rest-api-icon.png':
            return require('@/assets/images/skills/rest-api-icon.png');
        case 'graphql.png':
            return require('@/assets/images/skills/graphql.png');
        case 'jquery.gif':
            return require('@/assets/images/skills/jquery.gif');
        case 'php-round.png':
            return require('@/assets/images/skills/php-round.png');
        case 'laravel.png':
            return require('@/assets/images/skills/laravel.png');
    }
};   
